name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag antonsurv/docker-xcfem:$(date +%s)
    - name: Push the tagged Docker image
      run: docker push pjlamb12/angular-cli:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag antonsurv/docker-xcfem:latest
    - name: Push the latest Docker image
      run: docker push antonsurv/docker-xcfem:latest
